name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install -f

    - name: Login GitHub
      uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.GPAGES_TOKEN }}'

    - name : Deploy on GitHub Pages
      run: npm run deploy 